### ISSUE TITLE
Unit tests to add or explain

### ISSUE THREAD

**Issue by sarabodach** [pharmaverse/sdtmchecks#411]
Either add the below unit tests, unexport the function(s), or, explain if the functions are impractical or would required huge overhead, and said function cannot be unexported

- [x] requirement #0.110 'Remove non-ASCII characters from reported term in order for Pandoc to create PDF file' is not covered by any test ([convert_var_to_ascii](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/utils.R#L218-L252))
- [x] requirement #0.111 'Create .R file with sdtmchecks function calls' is not covered by any test ([create_R_script](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/utils.R#L491-L564))
- [x] requirement #0.112 'Create a sdtmchecks list object with column indicating whether the issue was previously seen' is not covered by any test ([diff_reports](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/utils.R#L571-L736))
- [x] requirement #0.124 'Save report as an xlsx file' is not covered by any test ([report_to_xlsx](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/utils.R#L320-L484))
- [x] requirement #0.126 'Run all data checks in sdtmchecks package using parallel processing' is not covered by any test ([run_all_checks](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/run_all_checks.R))
- [x] requirement #0.127 'Run a single check in sdtmchecks package' is not covered by any test ([run_check](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/run_check.R))
- [x] requirement #0.128 'Utility function to truncate data in var_name' is not covered by any test ([truncate_var_strings](https://github.com/pharmaverse/sdtmchecks/blob/devel/R/utils.R#L260-L313))
